### ISSUE TITLE
Styles for numbered and bulleted lists

### ISSUE THREAD

**Issue by tytax** [LarsGit223/dokuwiki-plugin-odt#101]
Numbered lists and bulleted lists have main text style now. Becouse of that it's hard to format big documents.

It will be great if each lists have their own style from standart OpenOffice styles.

thank you in advance.

**Comment by LarsGit223** [comment]
Done. Please test and give some feedback.

Style 'List 1 Content' is the paragraph style used for unordered/bulleted list content.
Style 'Numbering 1 Content' is the paragraph style used for ordered/numbered list content.

**Comment by LarsGit223** [comment]
I just changed the first paragraph style for the lists from automatic styles to common styles. The list content styles are the parents of the styles.

So you now also have the styles **First List 1 Content** and **First Numbering 1 Content**. You can use this e.g. to set the distance for the list to the previous content without changing the distance between the list items.

**Comment by tytax** [comment]
Thank you for your promt reply.

I reinstall odt plugin, but I see that the lists have the paragraph style the same as the basic text. Sometime I use MS Word to open odt documents. And Word has a opportunity to select all the text of one style. And in that case I can choose all lists in 1 click and change lists throught the whole document. In Open Ofiice you can change the paragraph style and it changes throught the whole document. But now the basic text and lists have the same style. It's too pity.
Could you do the different paragraph styles for basic text, numbered lists and bulleted list? Like for headings. They are different.
Or maybe i don't know how to apply you changes. I need to reinstall odt plugin, am i right?

**Comment by LarsGit223** [comment]
I just re-tested it, looks fine for me.

Please make sure that:
- you updated the ODT plugin (or reinstall)
- you changed the page you export before exporting it again. Otherwise you might get the cached version of the document which was still created with the previous version of the ODT plugin. In that case you get exactly the same file as before on export.

I for example changed the background-color of style **List 1 Content**, **Numbering 1 Content** and the normal text body to three different colors and I see three different colors. None of the styles did effect the others.

Please check again.

**Comment by LarsGit223** [comment]
You can also add ```~~NOCACHE~~``` at the start of your wiki page to make sure that the document you get is created new.

**Comment by tytax** [comment]
Good morning! 
I've just done what you say and it still doesn't work. But it is very important to me and my colleagues.
I changed the background-color of style the normal text body to green color in template.odt. And basic text, numbered list and bulleted list are green (![odt_test](https://cloud.githubusercontent.com/assets/15125539/10600801/cc15b338-7715-11e5-93a9-5f80a92a2e93.png))
This is a link to wiki where I'm testing your plugin. https://msk-raos.ru/dokuwiki-2015-08-10/doku.php
I did it opened to all. It's just new empty wiki with odt plugin, template.odt and 1 start page. Could you see what is wrong?

**Comment by LarsGit223** [comment]
![screenshotodtlist](https://cloud.githubusercontent.com/assets/9009011/10615518/9a9a0b2e-7760-11e5-82d9-2e05597e5be7.png)

Please have a look at the example screenshot. You should see the red marked styles if it works.

I possibly know why it is not working yet. I forgot that this change is only existing in the current master branch, not in the official release. So if you re-install or update using the plugin manager you just get the latest release again without the change.

If you want to use this change, you need to install it manually. Follow these steps:
- go to the dokuwiki extension manager
- click on the tab **manual install**
- enter the URL **https://github.com/LarsGit223/dokuwiki-plugin-odt/archive/master.zip** in the field **Install from URL**
- click install

I saw that you are using an ODT template. Unfortunately the master branch is the current development branch and is always work in progress. There are currently some issues regarding ODT templates, please see the issues here on github for more information. Especially see the issues reported by user **limelime**.

If you like some more information about what's also been changed and what work is in progress in the master branch, then please have a look at https://www.dokuwiki.org/plugin:odt:development.

**Comment by tytax** [comment]
Yes. Now it works. Thank you very much!

But I have some project on dokuwiki with many users and i worry about some possible problems that's why i don't update wiki. If it works fine I won't change anything. So, this wiki is DokuWiki 2014-09-29d Hrun.

And new version of odt plugin and this current branch with the newest changes don't work with old verson of wiki:
PHP Fatal error: no such method setConfigParam in /var/www/ … /[doku_wiki_directory]/inc/plugin.php on line 273

But it another different problem and maybe you have already know about it.

Anyway thank you again for your work.

**Comment by tytax** [comment]
I tested it. And it works incorrect with odt template.
Without odt template everything works fine. 
![without odt template](https://cloud.githubusercontent.com/assets/15125539/10632965/5037b672-77f0-11e5-9041-e8a16e0e8271.png)
This is template:
![odt template](https://cloud.githubusercontent.com/assets/15125539/10632974/5e4ec804-77f0-11e5-8be2-0aa0d4dae058.png)
And this is odt export with above template:
![with odt template](https://cloud.githubusercontent.com/assets/15125539/10632989/761219aa-77f0-11e5-9cee-0f7295d6337d.png)

**Comment by LarsGit223** [comment]
Hi,

sorry for the delay. Here is a little update:

> PHP Fatal error: no such method setConfigParam in /var/www/ … /[doku_wiki_directory]/inc/plugin.php on line 273

This is related to a bug in the ODT plugin. It is NOT related to an incompatibility between your version of Dokuwiki and the ODT plugin version. I think it should be fixed in the master branch (through #94 I assume).

> I tested it. And it works incorrect with odt template.
Without odt template everything works fine.

Some issues with ODT template have been sorted out in the meantime. I tested it with ODT template and it looks fine to me now. Please re-test.

**Comment by tytax** [comment]
Now everything works! Thank you very much!
![template works](https://cloud.githubusercontent.com/assets/15125539/10904909/a045d0ae-8227-11e5-98d9-38e27942f066.png)

**Comment by LarsGit223** [comment]
You are welcome.

**Comment by LarsGit223** [comment]
For your information:
I just added a new style for the last paragraph of a list. So you can now also easily control the distance to the content following a list. (only in master branch)

**Comment by tytax** [comment]
Hello!

This is related to a bug in the ODT plugin. It is NOT related to an incompatibility between your version of Dokuwiki and the ODT plugin version. I think it should be fixed in the master branch (through #94 I assume).

In #94 you fixed setParam() / getParam(), but I told about setConfigParam. So it doesn't still work with Wiki (hrun)
