### ISSUE TITLE
Table style from predefined odt has no effect anymore

### ISSUE THREAD

**Issue by limelime** [LarsGit223/dokuwiki-plugin-odt#102]
Table style from predefined odt has no effect anymore from the master branch.

Style your table in template.odt.
Add `{{odt>template:template.odt}}`.
Export. Table style is not there: no border line, no color, etc.

**Comment by limelime** [comment]
Same issue with Footer style.

**Comment by LarsGit223** [comment]
Could you please check if the fix for #103 also fixes the footer problem?

[It will not fix the table problem. The table has been assigned a own style, not the default table style. I'm still working on that]

**Comment by LarsGit223** [comment]
Seems also to be fixed by 7c6bbc23b6fa29a622dcc739034c387f7fc67a43. Please test.

Styles with the same name have not been overwritten anymore. The commit fixed that. I tested changing the background-color of a table and it worked.

**Comment by limelime** [comment]
Font-size from the predefined odt template has no effect.

**Comment by LarsGit223** [comment]
If I export a table it says font "Helvetica,arial..." size 9.7. Isn't that correct?

By the way, I could not use this document again. But after saving it in ODF format it worked. Before it seemed to be HTML document (writer).

**Comment by limelime** [comment]
Font-size should be 9. Download template.odt and open with libreoffice. Press F11. See screenshot.
![sss](https://cloud.githubusercontent.com/assets/8182563/10618494/4b8a72c0-773e-11e5-8153-4a362b99c548.png)



===========================


1) Add the following:
```
~~NOCACHE~~
{{odt>template:template.odt}}
^ Header 1  ^ Header 2  ^
| data 1    | data 2    |
```
2) Export.
![vvvvvvv](https://cloud.githubusercontent.com/assets/8182563/10618674/4c0a95da-773f-11e5-82f4-0db241ab63b0.png)

**Comment by LarsGit223** [comment]
I fixed some issues with style import/export. It looks fine for me now. Could you please re-test. Thanks!

**Comment by limelime** [comment]
It worked. Thanx!
