### ISSUE TITLE
No text formatting if ODT file used as template

### ISSUE THREAD

**Issue by LarsGit223** [LarsGit223/dokuwiki-plugin-odt#103]
If the ODT template is an ODT file, then after exporting a document no text formatting like underlined, italic etc... is shown. Just plain text.

**Comment by limelime** [comment]
Font size in footer is working but alignment is not. Everything is shift to the right side. The start of the footer is in the middle of the page.

**Comment by LarsGit223** [comment]
Hmmm...tested with the wrap plugin example page and 2 different ODT files as templates. Works fine for me.

How does your wiki code look like to produce the issue?

**Comment by limelime** [comment]
Here is a sample template file showing alignment issue in the footer: https://github.com/limelime/dokuwiki-plugin-odt/blob/master/test-data/template.odt

**Comment by LarsGit223** [comment]
Sorry, I can't use that template. It gives me an error when extracting it. I also get an error if I rename it to .zip and try to extract it on the desktop. But I can open it with LibreOffice - strange.
