### ISSUE TITLE
The wiki is unusable after the update  ( 17 Oct 2015 ) 

### ISSUE THREAD

**Issue by DarioGT** [LarsGit223/dokuwiki-plugin-odt#107]
Only returns a blank page

Console :  Failed to load resource: the server responded with a status of 404 (Not Found)  ( favicon.ico, doku.php )

**Comment by LarsGit223** [comment]
Which release do oyu use? Which PHP version do you use?

There are issues with older PHP versions, see #96.

**Comment by DarioGT** [comment]
PHP 5.3.3 (cli) (built: Jul  3 2015 03:10:33) 
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies


Ok  tkx

**Comment by DarioGT** [comment]
PHP 5.3.3 (cli) (built: Jul  3 2015 03:10:33)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies


Ok Thkx

2015-10-17 12:42 GMT-04:00 LarsGit223 <notifications@github.com>:

> Which release do oyu use? Which PHP version do you use?
>
> There are issues with older PHP versions, see #96
> <https://github.com/LarsGit223/dokuwiki-plugin-odt/issues/96>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LarsGit223/dokuwiki-plugin-odt/issues/107#issuecomment-148932739>
> .
>



-- 

Dario Gomez Tafur  MSc Ph.D. candidate
Prof. de recherche III CeRTAE
Département de SIO
Faculté des sciences de l'administration
Pavillon Palasis-Prince
Université Laval, Québec
Québec, G1V 0A6
