### ISSUE TITLE
Footer alignment in predefined odt template start from the middle

### ISSUE THREAD

**Issue by limelime** [LarsGit223/dokuwiki-plugin-odt#110]
Footer alignment in predefined odt template starts from the middle.
```
~~NOCACHE~~
{{odt>template:template.odt}}
```
template.odt can be found at https://github.com/limelime/dokuwiki-plugin-odt/raw/odt-v1.1/test-data/template.odt.

It is affecting the master branch. It was working fine in previous version.

**Comment by LarsGit223** [comment]
Thanks. This template can be used. Unfortunately I still do not get the problem. See the screenshot below:

![screenshotfootnote](https://cloud.githubusercontent.com/assets/9009011/10616064/814c3680-7763-11e5-8fe8-58ad1d8cf76a.png)

This was generated using your ODT template from the following wiki code:
```
~~NOCACHE~~
Hello World!

  * Text
  * More text

Normal text, normal text

  - Text
  - More text

Again normal text...

((Footnote test test test ...))
```
As you see the footnote starts on the left side. Maybe it is also specific to the wiki code itself. Can you please give me an example wiki code that is causing the issue in your installation.

Please also make sure you use the latest master. Thanks.

**Comment by limelime** [comment]
Don't add `((Footnote test test test ...))`. In your case, `testsite_state-4` should starts from the left, not from the middle.

Just don't add any text. Add 
```
~~NOCACHE~~
{{odt>template:template.odt}}
```
Simply export the odt file.
Compare template.odt and the exported odt file. You will see filename starts from the middle.

**Comment by LarsGit223** [comment]
Ahhh...sorry for confusing footnote and footer. I now see what you mean. I tested some templates of mine, no footer at all. Yours shows one starting at the middle.

Sorry, no more time for today. I will have a look at it tomorrow.

**Comment by LarsGit223** [comment]
I fixed some issues with style import/export. It looks fine for me now. Could you please re-test. Thanks!

**Comment by limelime** [comment]
It worked. Thanx!
