### ISSUE TITLE
Plugin breaks wiki

### ISSUE THREAD

**Issue by walterbe** [LarsGit223/dokuwiki-plugin-odt#124]
Hi,
My wiki is/was broken (blank page) and I have traced it down to this plugin.

On my real wiki the result was a blank page. In the PHP log I got the error;
PHP Fatal error:  Can't use method return value in write context in /home/gqowpzrh/public_html/lbc/lib/plugins/odt/helper/config.php on line 569

My line of the file at 569 is;
        if (!empty($this->getParam ('template')) && empty($this->getParam ('odt_template'))) {

By changing the premissions on the directory odt to none my wiki was back online.  But the main page is still gone and there is no menu to edit the page.

Then I have done the following test;
I installed a fresh default install of the current dokuwiki and installed the this plugin.

The result is;
main page is gone and the option the edit it also. The "admin" section, the profile section, recent changes, all does not work anymore.  Logout does work but you can not login again. The wiki is loaded, so I get no blank page like on the other wiki. But you can not do anything.

**Comment by LarsGit223** [comment]
This is a problem with older PHP versions.
In your config.php file at line 569 the code should now look like this:

```
$template = $this->getParam ('template');
$odt_template = $this->getParam ('odt_template');
if (!empty($this->getParam ('template')) && empty($this->getParam ('odt_template'))) {
    $this->setParam ('odt_template', $this->getParam ('template'));
}
```

Please edit that code section so that it looks like this:
```
$template = $this->getParam ('template');
$odt_template = $this->getParam ('odt_template');
if (!empty($template) && empty($odt_template)) {
    $this->setParam ('odt_template', $this->getParam ('template'));
}
```
So only line 569 itself need to be changed. Save the file and re-try. Your wiki should work again after that.

See issue #96 for more information.

**Comment by walterbe** [comment]
Thanks. I have upgraded from php 5.4 to php 7.0   and that seems to do it

**Comment by LarsGit223** [comment]
You are welcome. Nice to know that it works with php 7.0, didn't test it yet.
