### ISSUE TITLE
Templates selection gives priority to global config setting

### ISSUE THREAD

**Issue by NemChua** [LarsGit223/dokuwiki-plugin-odt#128]
When defining a default template in the configuration, it seems to supersede the template defined at the page level, in essence forbidding local definition of a template if there is one global one.

**Comment by LarsGit223** [comment]
I could reproduce the problem with the syntax ```{{odt>template:mytemplate.odt}}```.

Anyway ```template``` is supported for backwards compatibility but was re-named to ```odt_template```. On my installation it works fine if I use the syntax ```{{odt>odt_template:mytemplate.odt}}```.

Please try again with the ```odt_template``` syntax.

**Comment by NemChua** [comment]
...and it was in the docs --I ported a former wiki and did not notice.
Works great, thanks.

**Comment by LarsGit223** [comment]
You are welcome.
