### ISSUE TITLE
No separation between 2 consecutive tables

### ISSUE THREAD

**Issue by limelime** [LarsGit223/dokuwiki-plugin-odt#131]
There is no separation between 2 consecutive tables.
```
~~NOCACHE~~
^ Header 1  ^ Header 2  ^
| data      | data      |


^ Header 1  ^ Header 2  ^
| data      | data      |
```
![2 consecutive tables](https://cloud.githubusercontent.com/assets/8182563/14030256/23960a76-f1dd-11e5-8b14-c5fb220e59a8.png)

**Comment by LarsGit223** [comment]
I added a 0.25 top and bottom margin to the default table style. Should work now.
