### ISSUE TITLE
No separation between 2 consecutive tables in list using WRAP

### ISSUE THREAD

**Issue by limelime** [LarsGit223/dokuwiki-plugin-odt#132]
```
~~NOCACHE~~
  - Step 1.
  - Step 2.<WRAP>
^ Header 1  ^ Header 2  ^
| data      | data      |




^ Header 1  ^ Header 2  ^
| data      | data      |
</WRAP>
  - Step 3.

```

**Comment by LarsGit223** [comment]
Ok, should also work now.

Now, the default table style is copied/cloned for an indented table inside of  a list. So in future all changes done on the default table style should automatically also be applied to indented tables inside of a list.
