### ISSUE TITLE
Error in content.xml when note-tag in source

### ISSUE THREAD

**Issue by gerricom** [LarsGit223/dokuwiki-plugin-odt#144]
At one of our dokuwiki installations I have currently an issue exporting ODT files when a note (from [note plugin](https://www.dokuwiki.org/plugin:note).) is used in the source. 

Here is an example of an exported page: [intern-test-1.odt.zip](https://github.com/LarsGit223/dokuwiki-plugin-odt/files/277375/intern-test-1.odt.zip)

The source looks like this:

`<note>Test</note>`

And the error OpenOffice is giving me is a read-error in subdocument content.xml, position 62,111.

I'm pretty sure this should have worked in an earlier version of the ODT plugin, but I hadn't the time yet to setup a testing environment. 

Any thoughts, what's wrong here?

**Comment by LarsGit223** [comment]
Ooops...yeah that does not work any more.
Sorry, I did a lot of changes on the ODT plugin and did not test the note plugin for a while. My fault.

I managed to get it running again.
Please try the following:

- in your DokuWiiki installation folder open the file /lib/plugins/note/syntax.php
- try to find the following section:

```php
function render($mode, &$renderer, $indata) {
...
}
```

- replace all that lines with the following code:

```php
function render($mode, &$renderer, $indata) {

    if($mode == 'xhtml'){

      list($state, $data) = $indata;

      switch ($state) {
        case DOKU_LEXER_ENTER :
          $renderer->doc .= '<p><div class="'.$data.'">';
          break;

        case DOKU_LEXER_UNMATCHED :
          $renderer->doc .= $renderer->_xmlEntities($data);
          break;

        case DOKU_LEXER_EXIT :
          $renderer->doc .= "\n</div></p>";
          break;
      }
      return true;

    } elseif ($mode == 'odt'){

      list($state, $data) = $indata;

      switch ($state) {
        case DOKU_LEXER_ENTER :
          $type = substr($data, 4);
          if ($type == "classic") {
            $type = "note"; // the icon for classic notes is named note.png
          }
          $colors = array("note"=>"#eeeeff", "warning"=>"#ffdddd", "important"=>"#ffffcc", "tip"=>"#ddffdd");

          // Content
          $properties = array();
          $properties ['width'] = '100%';
          $properties ['align'] = 'center';
          $properties ['shadow'] = '#808080 0.18cm 0.18cm';
          $renderer->_odtTableOpenUseProperties($properties);

          $properties = array();
          $properties ['width'] = '1.5cm';
          $properties ['align'] = 'center';
          $renderer->_odtTableAddColumnUseProperties($properties);

          $properties = array();
          $properties ['width'] = '13.5cm';
          $renderer->_odtTableAddColumnUseProperties($properties);

          $renderer->tablerow_open();

          $properties = array();
          $properties ['vertical-align'] = 'middle';
          $properties ['text-align'] = 'center';
          $properties ['padding'] = '0.1cm';
          $properties ['border'] = '0.002cm solid #000000';
          $properties ['background-color'] = $colors[$type];
          $renderer->_odtTableCellOpenUseProperties($properties);

          $src = DOKU_PLUGIN."note/images/".$type.".png";
          $renderer->_odtAddImage($src);

          $renderer->tablecell_close();

          $properties = array();
          $properties ['vertical-align'] = 'middle';
          $properties ['padding'] = '0.3cm';
          $properties ['border'] = '0.002cm solid #000000';
          $properties ['background-color'] = $colors[$type];
          $renderer->_odtTableCellOpenUseProperties($properties);
          break;

        case DOKU_LEXER_UNMATCHED :
          $renderer->cdata($data);
          break;

        case DOKU_LEXER_EXIT :
          $renderer->tablecell_close();
          $renderer->tablerow_close();
          $renderer->_odtTableClose();
          $renderer->p_open();
          break;
      }
      return true;
    }
    
    // unsupported $mode
    return false;
} 
```

The note plugin creates it's own styles by directly adding them to the styles array in the ODT renderer. This is not supported any more.

But I should have remembered to test it. Sorry for the inconvenience.

Please let me know if the code above is working at your site to and then I will create a pull-request for the note plugin. Thanks in advance!

**Comment by gerricom** [comment]
Thanks for your response! It works well! The ODT export is working perfectly nice again!

**Comment by LarsGit223** [comment]
Good news!

I am still waiting for a reaction of the maintainer of the note plugin. Not sure if it is still actively maintained. So the fix is not included in the official version yet.

Therefore I leave this issue/thread open for now.

**Comment by LarsGit223** [comment]
I created a pull-request in the note plugin repository. So I close this now.
