### ISSUE TITLE
Render from Action PlugIn?

### ISSUE THREAD

**Issue by andyboeh** [LarsGit223/dokuwiki-plugin-odt#149]
How can I render from an action PlugIn, such as "publish", to the ODT file? Is there an event that allows me to postprocess the XML output before it is zipped? I would like to have the publishing information (i.e. page approved or not) visible in the ODT file.

Thanks

**Comment by LarsGit223** [comment]
No, actually the ODT plugin does not fire any events.

I assume it would be possible to change it. I have to admit that I do not have any experience with writing action plugins. So I would need help/contributions for that.

What would be the workflow of such a change/how would the content be changed?
If the planned workflow would be like this:
- ODT document is rendered (from action plugin)
- ODT plugin fires an event before the document is zipped and sent
At this point how do you want to specify where to insert the data/changes?

I only had a short look at the publish plugin page. I do not use it myself. Could you provide a screenshot giving me an idea how it looks in the browser?

**Comment by LarsGit223** [comment]
P.S.:
Didn't you contribute the changes for **returnonly** and **disable/enable links**?
I am just working on a major redesign of the ODT plugin (see branch **redesign**). If you like and if  you got the time it would be nice if you could test if that two features still work fine for you using branch **redesign**. Of course only if you like.

**Comment by andyboeh** [comment]
The workflow of the action plugin is as follows:
DokuWiki fires the event TPL_ACT_RENDER before the rendering of the actual page content is started. Then, publish writes its HTML output directly to the browser (it bypasses the renderer, e.g. https://github.com/cosmocode/dokuwiki-plugin-publish/blob/master/action/banner.php). Afterwards, the rendering of the page is started using the selected rendering plugin. In an action PlugIn, the renderer is usually not available. Furthermore, TPL_ACT_RENDER is only invoked for XHTML output.

There is an event called RENDERER_CONTENT_POSTPROCESS available, but at this stage the ODT output has already been compressed.

I found an old plugin called 'tablewidth' that attaches to an event called 'PLUGINODT_CONTENT_ADDZIP', where this particular plugin added output to the XML file: https://github.com/cosmocode/dokuwiki-plugin-tablewidth/blob/master/action.php

Yes, I contributed the mentioned changes. I'd be happy to test the changes, but it's going to take a few days.

**Comment by LarsGit223** [comment]
> Yes, I contributed the mentioned changes. I'd be happy to test the changes, but it's going to take a few days.

That would be great. Please do not hurry. There is enough work left on the branch. I am not planing to release it soon so you are not slowing me down or something.

> I found an old plugin called 'tablewidth' that attaches to an event called 'PLUGINODT_CONTENT_ADDZIP', where this particular plugin added output to the XML file: https://github.com/cosmocode/dokuwiki-plugin-tablewidth/blob/master/action.php

I did not find the string 'PLUGINODT_CONTENT_ADDZIP' anywhere in the ODT plugin. So I assume it would not work (anymore?). Also, the plugin is not listed at https://www.dokuwiki.org/plugin:odt:rendersupport.

So would I just need to fire the event and pass a pointer to the not zipped document content (so to $renderer->doc). Or would you like a pointer to the renderer object and call a function?

If you use ODT files as a template we could also think about defining a field in the ODT template file and let it be filled from the publish plugin (see plugin fields, https://www.dokuwiki.org/plugin:fields).

I will also take some time and look a bit more into the publish plugin.

**Comment by andyboeh** [comment]
Thanks, actually, I just wanted to know if there is an easy way to achieve what I want :)

I'll look into it next week and let you know once I come up with something. I wasn't aware of the fields functionality, looks interesting, thanks for pointing that out!

**Comment by LarsGit223** [comment]
> Thanks, actually, I just wanted to know if there is an easy way to achieve what I want :)

Well actually not :-(
But if you have got the time we can work on it. But I can not say or promise anything about how long it will take.

**Comment by LarsGit223** [comment]
I installed the publish plugin to see how it looks like.

So I guess you "only" need the banner in the exported ODT file. I suggest to not use some event but maybe write a function in the publish plugin to let the ODT plugin query the status of the page. And in the ODT plugin I suggest to have a config option like "insert publish banner page as..." with the option "first page" or "last page". And then also a config option for a banner template page. This page could be rendered by the ODT plugin on export and the Fields or Bureaucracy plugin could be used to fill in the values queried from the publish plugin.

But this is not really what your question was.

So, again, there is actually no event letting you render into/postprocess the finished ODT file before it is zipped and delivered. Also, the future "redesign" branch will not allow direct access to **$renderer->doc** (or better say the document content will not be stored there any more, only at the end the zip file will be assigned to $renderer->doc).

The other point is ODT support by the publish plugin. I will close this question and open a new issue as a feature request and also open an issue in the publish plugin to add the author to the discussion.
