### ISSUE TITLE
ODT Export icon show blank page

### ISSUE THREAD

**Issue by limelime** [LarsGit223/dokuwiki-plugin-odt#153]
When ODT Export icon is clicked, it showed blank page.  After the following commit, it doesn't work anymore.
https://github.com/LarsGit223/dokuwiki-plugin-odt/commit/7e96929e591d3e70afe8f93c7f238fd22a0454b8

**Comment by LarsGit223** [comment]
Hmmm...I fixed an issue related to tables being nested in a list.
But that fix doesn't seem to be related to the commit you referenced.

Please check if the change in master solves your problem.
If not, please specify an example wiki code which reproduces the problem. Thanks.

**Comment by limelime** [comment]
Hi LarsGit223, in my initial description, the keyword is **after** the commit https://github.com/LarsGit223/dokuwiki-plugin-odt/commit/7e96929e591d3e70afe8f93c7f238fd22a0454b8.

On commit https://github.com/LarsGit223/dokuwiki-plugin-odt/commit/a585703e4a29cc5512b04759a70da031fa729982 forward, clicking on the export icon show blank page.

I already tried on master and got the same issue. So I traced back to these commits.

**Comment by LarsGit223** [comment]
So do you still get the problem after the change I committed to master yesterday?

If yes, please post some example wiki content which causes the problem.
(I did some test with my test pages and only found the problem with the nested tables so far, that has been fixed yesterday)

**Comment by limelime** [comment]
Thx LarsGit223. It is now working fine with yesterday's commit (https://github.com/LarsGit223/dokuwiki-plugin-odt/commit/6e73cc52e952c34981a8f30f5b7a7f28fadaadfa).
