### ISSUE TITLE
Can't open ODT export containing a 'dos' codeblock

### ISSUE THREAD

**Issue by Kevin-NZ** [LarsGit223/dokuwiki-plugin-odt#158]
Hi, I'm having some trouble when exporting pages containing 'dos' codeblocks.  In order to open the exported document I need to change the codeblock to 'txt' (ie no markup).  Obviously a clash between the 'dos' markup and the ODT export.  I'm running a fairly standard install of dokuwiki so hopefully the following will be easily replicated.

The following is an example of a line within a BAT file that causes the failure:

`<code dos ODT_Export_Issue.bat>`
`for /F %%i in ("%1") do set file=%%~ni`
`</code>`

and the following is a minimal example of a wiki page that fails to open (after being exported):

`<code dos ODT_Export_Issue.bat>`
`for %i in ("1")`
`</code>`

This is not a big problem, just thought I'd provide feedback on this great plugin.

**Comment by LarsGit223** [comment]
Thanks for reporting the issue. I will have a look at it as soon as I got time for it.

**Comment by LarsGit223** [comment]
The issue is fixed. The change is not released yet but included in the development/master branch.

Thanks for reporting the issue!

**Comment by LarsGit223** [comment]
The problem always occurred in case a code block included multiple (more than one) keyword links.
