### ISSUE TITLE
PDF support is well hidden :)

### ISSUE THREAD

**Issue by fpoto** [LarsGit223/dokuwiki-plugin-odt#162]
While a button exists for conversion to ODT, a special URL must be crafted to create PDF. Ideally, the same button used for ODT could pop a menu with two entries, for creating ODT or PDF.

**Comment by LarsGit223** [comment]
Well, that's true and I am aware of it.
I did not want to automatically add a PDF button because PDF export in the ODT plugin is quite new and PDF export is also provided by the dw2pdf plugin.

I will have to think about a good solution.

**Comment by fpoto** [comment]
Well, adding a new button is too much. Is the solution I had proposed feasible at all?

**Comment by LarsGit223** [comment]
I will have to talk about other developers about that. I found examples of HTML and CSS based menus on the web but it needs to integrate with all the dokuwiki templates and I don't know how that works.

**Comment by Klap-in** [comment]
Is it not a simpler solution to create a second button for pdf export? With an own configuration setting. 
And prevent a complicated double usage button?

**Comment by LarsGit223** [comment]
It is definitely much simpler I guess. Even the buttons that we have  do not work well with all dokuwiki templates (also I assume that's a problem in the templates code if buttons do not work 100% well).

I think for now I will go with a second ODT plugin button for PDF export which can be enabled/disabled in the configuration.
