### ISSUE TITLE
Ampersand in text:user-field-decls crashes ODT export

### ISSUE THREAD

**Issue by aloishockenschlohe** [LarsGit223/dokuwiki-plugin-odt#182]
In file renderer/page.php the values of text:user-field-decls are exported into the ODT:

   $value = '<text:user-field-decls>';
   foreach ($this->fields as $fname=>$fvalue) {
       $value .= '<text:user-field-decl office:value-type="string" text:name="'.$fname.'" office:string-value="'.$fvalue.'"/>'; 
   }

If one of the values contains the char "&", the resulting ODT is broken.
Fix: Use the PHP function htmlspecialchars.

$value .= '<text:user-field-decl office:value-type="string" text:name="'.htmlspecialchars($fname, ENT_QUOTES, 'UTF-8').'" office:string-value="'.$fvalue.'"/>'; 

Regards

Alois

**Comment by LarsGit223** [comment]
Hi Alois,
thanks for reporting the issue.
I am **not** getting the issue with the current version of the fields plugin and the master/development version of the ODT plugin. I tried the following examples to cause an error:
```
{{fields>FIE&LD_NAME=FIELD_VALUE}}
{{fields>FIELD_NAME=FIELD_VAL&UE}}
```
 What versions do you use?

Kind Regards, Lars

**Comment by aloishockenschlohe** [comment]
Hi Lars!

According to my DokuWiki installation I am working with the latest release (2016-09-10).
I took a look at the code in the repository and realised that a lot of things changed.
Couldn't find the code I mentioned in my first post.

I think the issue can be closed. Sorry for the false alarm...

Alois

**Comment by LarsGit223** [comment]
Hello Alois.
No need to worry. Better a already solved issue than a possibly unreported issue.
Regards, Lars
