### ISSUE TITLE
Conflict with the dokuwiki panel configuration

### ISSUE THREAD

**Issue by EPN-anim** [LarsGit223/dokuwiki-plugin-odt#185]
Hi,
the last update from february 2017 break the access to the panel configuration of dokuwiki. The page is blank.
When I uninstall the plugin, I can access to the  #panel.
My dokuwiki is installed on a debian with the deb package.
Thx

**Comment by LarsGit223** [comment]
Hello,
thanks for reporting the issue. I am not sure what you mean.

Do you mean you go to Administration and then configuration settings and then you get the blank page?
If yes, it works fine on my system.

What DokuWiki version are you using?

Regards,
Lars

**Comment by LarsGit223** [comment]
The current release of this plugin is backwards compatible up to/including DokuWiki release 2015-08-10 “Detritus”.

**Comment by EPN-anim** [comment]
yes, you understood what i meant.
My version is «Release 2014-05-05a "Ponder Stibbons"»… so that might be the problem. That's the package in the debian repo, I imagined it was the newest I could have.
I'll try to upgrade.
Thanks for the answer, and the plugin.
Regards.

**Comment by EPN-anim** [comment]
The debian jessie dokuwiki release is the 2014 one… In debian sid, dokuwiki is on 2016 release.

**Comment by LarsGit223** [comment]
Please see https://www.dokuwiki.org/plugin:odt#requirements. At least you need release "Detritus". But I strongly recommend to update to the latest DokuWiki release if you can.

Anyway, the ODT plugin should not crash the extension manager on not compatible/older releases. I will prepare a quick fix to not break the extension manager on to old DokuWiki releases. Instead I will generate an error page if ODT export is started. I guess I'll bring out the fix at the upcoming weekend.

**Comment by LarsGit223** [comment]
But please keep me up to date about your update process and the result.

**Comment by EPN-anim** [comment]
Well, I've downloaded the .deb stretch package, and I installed it manually with a 'dpkg -i dokuwiki….deb' command. There was an error about php and php-xml dependencies missing, but my Dokuwiki seems to be work anyway. It's now on "Elenor of Tsort" version, and the issue on the panel configuration disappeared.
Problem solved. ;)
Thx

**Comment by LarsGit223** [comment]
You are welcome, thanks again for reporting the issue. So I close this now but I opened issue #186 as an enhancement to fix the extension manager problem for older releases anyway.
