### ISSUE TITLE
Crash when exporting multiple tables on page on first try (Division by zero)

### ISSUE THREAD

**Issue by fstorck** [LarsGit223/dokuwiki-plugin-odt#197]
Latest version (2017-04-01) crashes when trying to export more than one table ( see page code). Seems to be dependant on caching, since the 2nd export trial seems to work usually. 
[callstack.pdf](https://github.com/LarsGit223/dokuwiki-plugin-odt/files/892748/callstack.pdf)

`^ Spalte 1 ^ Lange Spalte 2 ^ Spalte 3 ^ 
| adbklasdb  | | |
| | sdlfkjsdklf  | lskjdlfksjf |

^ Spalte 1 ^ Lange Spalte 2 ^ Spalte 3 ^ 
| adbklasdb  | | |
| | sdlfkjsdklf  | lskjdlfksjf |`

**Comment by LarsGit223** [comment]
Hmmm...I have exported the two tables above more than10 times, no crash. Even with disabled cache.

How does your ODT configuration look like? Are you using a template for export?

**Comment by LarsGit223** [comment]
I also appended all example tables from the syntax page at dokuwiki.org to my test page. No success, still no crash.

**Comment by fstorck** [comment]
Hi Lars,
it may be depending on my default template. The page I was testing had no template set, but I think I forgot the global settings. I'll check that tomorrow.

**Comment by fstorck** [comment]
Hi Lars, 
I tried it with removing my standard template. However, the first render attempt seems to fail mostly. I think, I have no other plugins interfering in this special case. It seems to be a cache related issue. I could reproduce the failure after deleting the cache and retry an export. The first attempt failed ( with no template set in wiki configuration) and following events were successfull. Clearing the cache and following export failed again.

**Comment by LarsGit223** [comment]
Could you post a screenshot of your complete ODT settings. Just to be sure we do not oversee something.

**Comment by LarsGit223** [comment]
The screenshot is not required any more. The problem should be fixed.

I could create the problem by rendering the test page in the unit testing code. I have no idea why it does not happen in my normal DokuWiki environment. :question::question::question:

**Comment by fstorck** [comment]
Seems to be fixed in current master
