### ISSUE TITLE
ODT export icon "jumps"

### ISSUE THREAD

**Issue by swiehr** [LarsGit223/dokuwiki-plugin-odt#210]
The ODT export action icon "jumps" on click to the left of the containing box (see screenshot) and stays like that (unfortunately not when trying to inspect this via browser)
![odt-export-icon-jump](https://user-images.githubusercontent.com/14979596/28780366-bae2fcf0-7606-11e7-9a85-2909ceaa801c.jpg)

**Comment by LarsGit223** [comment]
Thanks for reporting the issue. Should be fixed now in current master.
