### ISSUE TITLE
Support new menu system type buttons

### ISSUE THREAD

**Issue by splitbrain** [LarsGit223/dokuwiki-plugin-odt#212]
The way how menus are built will change in the next DokuWiki release (see https://www.patreon.com/posts/menus-14160215). The plugin should be adjusted to add its button through the new MENU_ITEMS_ASSEMBLY event.

**Comment by LarsGit223** [comment]
This is "work in progress", see branch ```NewActionAndMenu```.

**Comment by LarsGit223** [comment]
Implemented/Closed by merging PR #232.
