### ISSUE TITLE
ODT export → Fatal error:  Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by daniel-szwed** [LarsGit223/dokuwiki-plugin-odt#218]
When I was trying to ODT export the following error was appeared in logs:
==> /var/log/apache2/error.log <==
[Sat Oct 28 20:47:29.946004 2017] [:error] [pid 1603] [client 192.168.1.19:51166] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/lib/dokuwiki/lib/plugins/odt/ODT/css/cssimportnew.php on line 213, referer: http://169.254.74.127/dokuwiki/doku.php?id=development:development&do=

==> /var/log/apache2/access.log <==
192.168.1.19 - - [28/Oct/2017:20:46:59 +0000] "GET /dokuwiki/doku.php?id=development:development&do=export_odt HTTP/1.1" 500 324 "http://169.254.74.127/dokuwiki/doku.php?id=development:development&do=" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"

I am currently running DokuWiki Release 2017-02-19e "Frusterick Manners" on Apache2

Hardware: Raspberry Pi v 1 model B+ with Rasblian

My php version is:
PHP 5.6.30-0+deb8u1 (cli) (built: Apr 14 2017 16:20:58)

Odt plugin was installed via Extension Manager.

**Comment by LarsGit223** [comment]
I assume that the plugin was simply to slow to create the exported document in 30 seconds. You could try this workarounds:
- split the page to export into smaller parts/pages
- run dokuwiki on a faster machine
- increase the time that PHP allows skripts to run (default is 30 seconds)

You can change the maximum execution time in your ```php.ini``` file. On my Ubuntu system the file is stored under the path ```/etc/php/7.0/apache2/php.ini```. Search for the setting ```max_execution_time``` and change it. You might need to restart apache to use the new settings. E.g. the code below sets the maximum execution time to 10 minutes:
```
; Maximum execution time of each script, in seconds
; http://php.net/max-execution-time
; Note: This directive is hardcoded to 0 for the CLI SAPI
max_execution_time = 600
```

**Comment by daniel-szwed** [comment]
I've edited php.ini file according your instruction and I've restarted the server.
Now everything is working fine (time of rendering is a little bit over half minute for page with small content).
It was just configuration problem instead error like in the issue title (forgive me I'm not developer).
Thank you for the very quick response.
Best regards,
Daniel Szwed

**Comment by LarsGit223** [comment]
> It was just configuration problem instead error like in the issue title (forgive me I'm not developer).

No problem. From the outside you could not differ between an real endless loop or just a timeout issue.

> Thank you for the very quick response.

You are welcome.
