### ISSUE TITLE
$ACT is modified even if no action is taken

### ISSUE THREAD

**Issue by micgro42** [LarsGit223/dokuwiki-plugin-odt#226]
https://github.com/LarsGit223/dokuwiki-plugin-odt/blob/0922960269e6c5f6bb5093dcb2797c45717fc879/action/export.php#L108

The `$ACT` global variable is always modified even if no action is taken by this plugin. While the specific modification (i.e. replacing it with cleaned `$ACT`) is not wrong per se, it unnecessarily breaks other plugins that are listening for their own `?do=` key, if that key includes uppercase letters.

suggested fix:
1) use early return before modifying any globals if this isn't the plugin's action
2) use only `$event->data`, not `$ACT`

**Comment by LarsGit223** [comment]
@micgro42: I have changed this before but obviously forgot to commit and push it. Thanks for posting this issue.
