### ISSUE TITLE
Can't open odts from certain pages 

### ISSUE THREAD

**Issue by 5870guy111** [LarsGit223/dokuwiki-plugin-odt#227]
Hey,

I made a python script that fixes up formatting issues with the odt2dw plugin, and also converts tables to exttab3 syntax, however, when i try to run your plugin on these pages i get the following error. 

"we're sorry. we can't open {file} because we found a problem with its contents."

clicking details gives:

"Unspecified error"

"Location: Part: /content.xml, Line:0, Column:0"

Nothing in the python script changes anything that couldn't be changed by altering the page by hand. What could be making this error?

**Comment by LarsGit223** [comment]
I assume that the exported odt file is corrupted. That means something in the wiki source could lead to a bug in the odt plugin making it generate an invalid odt document.

Can you provide the page's wiki syntax which is causing this problem? Or that part of the page which is causing the problem. You mentioned exttab3 syntax. Maybe only the table is enough to cause the problem.

**Comment by LarsGit223** [comment]
@5870guy111: any news? I need some input to help you with this issue. Otherwise I can't help you.

**Comment by LarsGit223** [comment]
@5870guy111: do you still have this issue with release 2018-05-05?

**Comment by LarsGit223** [comment]
@5870guy111: why did you close this? Did you find a workaround? Please give some feedback.
