### ISSUE TITLE
Format error discovered in the file in sub-document

### ISSUE THREAD

**Issue by sioc-de-narf** [LarsGit223/dokuwiki-plugin-odt#229]
Hi,

I try do convert big and long pages with div, tables , images, etc.

I get the error :

Format error discovered in the file in sub-document content.xml at 443,15604(row,col)

File attached.

Thanks

[fatecore_t2-les_bases.zip](https://github.com/LarsGit223/dokuwiki-plugin-odt/files/1829870/fatecore_t2-les_bases.zip)
.

**Comment by LarsGit223** [comment]
Hello,
sorry for the inconvenience and thanks for reporting the issue. Unfortunately the document you added is quite large and it's hard to find the broken XML element.

Could you try to cut some parts of the document so that you get a smaller document which still produces the problem?

Regards,
Lars

**Comment by sioc-de-narf** [comment]
ok i shrunk down the trouble...

new error message :

Erreur de lecture.
Format error discovered in the file in sub-document content.xml at 106,1058(row,col)

and the file is smaller :)


I use the bootstrap3 template and the page content is :

`
==== Invoquer un aspect ====

<wrap indent></wrap>**Afin d’avoir droit au bonus, vous devez également expliquer ou justifier en quoi l’aspect vous aide.**
`

**Comment by sioc-de-narf** [comment]
damn forgot the file ... :)
[test error export.zip](https://github.com/LarsGit223/dokuwiki-plugin-odt/files/1837552/test.error.export.zip)

**Comment by sioc-de-narf** [comment]
grrr it change the code cop / paste ..

`==== Invoquer un aspect ====

<wrap indent></wrap>**Afin d’avoir droit au bonus, vous devez également expliquer ou justifier en quoi l’aspect vous aide.**
`

**Comment by sioc-de-narf** [comment]
you can see the code here ... http://pasted.co/83c9444f

**Comment by LarsGit223** [comment]
Thanks, I can re-produce the problem now.

The empty wrap tag is causing the problem. It shouldn't cause problems and I will try to fix it. Anyway, there is a workaround that you could use:

Instead of writing:
```
<wrap indent></wrap>**some bold text**
```
You can write:
```
<wrap indent>**some bold text**</wrap>
```

FYI: ```<wrap indent>``` will only indent the first line of a paragraph while ```<WRAP indent>``` will indent the complete paragraph.

**Comment by LarsGit223** [comment]
Ok, I fixed the issue. Now, the empty ```<wrap indent></wrap>``` will not break the exported document. 

But the result will be different than seen in the browser in this case. The browser will show an indented text, the exported document will not. For the ODT export you have to place the ```<wrap>``` tags around the text.

**Comment by drwetter** [comment]
I ran into the same issue now. Plugin has is from July 2019.

If I open the document straight away with libreoffice I get the (sorry, German) message **Formatfehler in Teildokument content.xml bei 2324,10(Zeile,Spalte) in der Datei entdeckt.** . When I open in the archive the content with ark I get a similar  message in English **error on line 2324 at column 10: Opening and ending tag mismatch: note-body line 0 and p**.

xmllint:

```
content.xml:2324: parser error : Opening and ending tag mismatch: note-body line 2323 and p
</text:p></text:note-body></text:note><text:p text:style-name="Text_20_body">, w
         ^
content.xml:2324: parser error : Opening and ending tag mismatch: note line 2323 and note-body
</text:p></text:note-body></text:note><text:p text:style-name="Text_20_body">, w
                          ^
content.xml:2324: parser error : Opening and ending tag mismatch: p line 2323 and note
</text:p></text:note-body></text:note><text:p text:style-name="Text_20_body">, w
                                      ^
```

**Comment by drwetter** [comment]
FYI: I can't hand over the documents, sorry. But I had in the two documents in question a footnote ``(())`` which contained code sections. Once I converted the footnote from ``(())`` --> ``()`` it worked.
