### ISSUE TITLE
DW2odt not working anymore after DW upgrade to "Greebo"

### ISSUE THREAD

**Issue by falkov237** [LarsGit223/dokuwiki-plugin-odt#233]
The export-button is vanished. Activate it in the admin section makes no difference. Inserting ~~ODT~~ for exports of a single page gives a blank screen.

**Comment by dg1atn** [comment]
Hi, 

it seems to be the same problem dw2pdf had. 

 Call to undefined function css_styleini() in /lib/plugins/odt/helper/dwcssloader.php on line 59,

Thanks for fixing...

**Comment by LarsGit223** [comment]
@dg1atn: thanks for the info, that saved me some time :thumbsup:

@falkov237: both problems should be fixed now with the just released new version.

Both: please update and re-try.

**Comment by falkov237** [comment]
Thanks, the new version fixes the problem!
