### ISSUE TITLE
Config show...button don't work

### ISSUE THREAD

**Issue by dg1atn** [LarsGit223/dokuwiki-plugin-odt#236]
Hi,

both config issues do not work.

plugin»odt»showexportbutton 

plugin»odt»showpdfexportbutton

Both are set to 0 in conf/local.php but the button are still visible on the edit pages. 
I use Release 2018-04-22 "Greebo" and latest plugin version.

Thanks for help...
TobbY

**Comment by LarsGit223** [comment]
I have fixed this already but haven't released a new version yet. You might install the development version manually to test it (that means go to the DokuWiki extension manager and select the tab "Manual Install" and install from this URL: https://github.com/LarsGit223/dokuwiki-plugin-odt/archive/master.zip).

**Comment by dg1atn** [comment]
I install with your link and it seems to work well. When do you plan to release this developmet version?

**Comment by LarsGit223** [comment]
I think I will wait until next weekend to see if any other problems are reported.

**Comment by LarsGit223** [comment]
The new release 2018-05-05 is out now.
