### ISSUE TITLE
Warning: Use of undefined constant self - assumed 'self' 

### ISSUE THREAD

**Issue by schplurtz** [LarsGit223/dokuwiki-plugin-odt#246]
Hi,

Whith php 7.3.6, here is what I get in libreoffice when I try to open an odt document generated by the odt plugin :
<img width="900" alt="image" src="https://user-images.githubusercontent.com/1008292/60752811-651b2a00-9fca-11e9-87ed-3e8e8ff2dc36.png">

Here is the faulty line.
https://github.com/LarsGit223/dokuwiki-plugin-odt/blob/19d878a9b94ad48769fda5c3b85418942939b6f2/ODT/ODTUtility.php#L979

As suggested on https://stackoverflow.com/a/18406758, I blindly replaced `self` with `__CLASS__` and everything worked as expected.

The problem appeared on this page if that matters :
```
<code C fragment.c>
    printf( "Hello World !\n" );
</code>
```

**Comment by LarsGit223** [comment]
Fixed. Thanks for reporting the issue :+1:
