### ISSUE TITLE
Table of contents not generated

### ISSUE THREAD

**Issue by intervisionlord** [LarsGit223/dokuwiki-plugin-odt#250]
In settings i have filled options - toc_maxlevel, toc_leader_sign, toc_indents
but in formed document there is no any table of contents

**Comment by LarsGit223** [comment]
See https://www.dokuwiki.org/plugin:odt#toc. You need to insert the syntax tag ```{{odt>toc}}``` in you wiki page to generate a table of contents. It will not change the HTML output, only the exported document is affected.

**Comment by LarsGit223** [comment]
A little remark: the plugin does not genearte/know the exact page numbers. You will need to update the toc once after opening the exported document.

**Comment by intervisionlord** [comment]
Thanks for reply. This helps partically.

> It will not change the HTML output, only the exported document is affected.

But it does:
![cbbbb84a9122fd8294305022d741e02e.png](https://dropimg.ru/images/2019/11/09/cbbbb84a9122fd8294305022d741e02e.png)

It adds note saying "TOC would be here" (actually IDK is it because of template or not)

Workaround: Using the "hidden" plugin and placing code between `<hidden></hidden>` container solved this...

**Comment by LarsGit223** [comment]
> Workaround: Using the "hidden" plugin and placing code between <hidden></hidden> container solved this...

You can use the plugin's config option ```index_in_browser``` to achieve the same result. Set it to ```hide```.

**Comment by intervisionlord** [comment]
Doesn't work. Placeholder still shown. =(

**Comment by LarsGit223** [comment]
Just re-tested. Works for me. Maybe you have to clear the cache of that page, see https://www.dokuwiki.org/devel:caching?s[]=purge#purging_the_cache.

**Comment by intervisionlord** [comment]
Clearing cache does not help. Anyway i use `<hidden>` tag now and it's okay...
Thank you.
