### ISSUE TITLE
Call to undefined method ODTElementParagraph::getListLastParagraphPosition()

### ISSUE THREAD

**Issue by mark-prins** [LarsGit223/dokuwiki-plugin-odt#254]
This error was being thrown when exporting to ODT from [this page](https://docs.msupply.org.nz/faq:install_remote_support_software)

`Uncaught Error: Call to undefined method ODTElementParagraph::getListLastParagraphPosition() in /home/msupply/public_html/docs/lib/plugins/odt/ODT/ODTList.php:57`

I've changed line 57 in `ODTList.php` to this, in order to work around the error and the page now exports ok

```
        if(function_exists($list->getListLastParagraphPosition)) {
            $position = $list->getListLastParagraphPosition();
        }
```

**Comment by LarsGit223** [comment]
Hi Mark,

thanks for reporting the issue. I fear that your code change might be wrong. As I do not have the page source and so cannot re-produce the problem myself could you please test the following:

1. revert your changes
2. instead change line 54 in ```ODTList.php``` from
```
    $list = $params->document->state->getCurrent();
```
to
```
    $list = $params->document->state->getCurrentList();
```
3. Re-test exporting the page to ODT

It would be great to get the test results and see if that fixes it. Thanks in advance.

**Comment by mark-prins** [comment]
Hi @LarsGit223 - thanks for following up!
Yes, you are spot on - I've reverted the change above, checked that I still get the error, then  changed line 54 to 

```
    $list = $params->document->state->getCurrentList();
```

and the ODT exports.

There is a follow up error, which I expect is unrelated.. the resulting document won't open ( tried LibreOffice which is my default for ODT files, and then Word ). LibreOffice gives me 

<img width="535" alt="Screen Shot 2020-09-01 at 5 44 00 PM" src="https://user-images.githubusercontent.com/9192912/91799503-4c181280-ec7b-11ea-8079-9fbe73b3eab8.png">

but let's ignore that one for now 😉

**Comment by LarsGit223** [comment]
Thanks for the quick test :+1: The change is now included in the master branch.

I will check the broken document later. There was a fix lately for a issue related to foot notes including code section, see #252. But I assume it's not very likely that that is also your issue left here.

**Comment by LarsGit223** [comment]
@mark-prins It looks like the exported document is broken because a paragraph is not closed properly. Unfortunately my test pages all export well without errors. If you got the time it would be great if you could open a new issue regarding the export error and include the wiki page content in that issue. I don't need the images, just the wiki text (if possible).

**Comment by mark-prins** [comment]
Awesome - thanks! Created #255
