### ISSUE TITLE
quote conversion

### ISSUE THREAD

**Issue by jlrn7** [LarsGit223/dokuwiki-plugin-odt#31]
Hello! 

The plugin does not convert standard quotation formatting with the gt headed paragraph  like

    > this one
> this one.

I don't know if this is a bug.

**Comment by LarsGit223** [comment]
Hi,

well, it seems like this is currently not implemented. The question is how this could be displayed in ODT. One solution would be to use a table which only has a border on the left side.

Do you have any suggestions how this should look like in ODT? Would an implementation with tables be fine for you?

Greetings,
Lars

**Comment by jlrn7** [comment]
I think it might be better to define a paragraph style called "quotation", or something like that, which adds some left and right paragraph indentation, and apply that style to the quoted text in the conversion. That way, the end user may change the display of all quotations simply modifying that paragraph style. 

If I understand the code (I'm a php and odt newbie, sorry!), that style should be added in the definition the _getInitStyles function in renderer.php; then define the corresponding function _quotation (or something), and finally add the pattern matching to apply this style to the text. Perhaps you'll have to change the styles.xml file to add this style. As to how to parse the string \n> in the source file and apply the style, I'm totally in the dark.

Cheers,
Louis.

**Comment by LarsGit223** [comment]
Hi Louie,

in general having a style which can be changed by the user is a good idea. But if we use a paragraph style we will not have the same look as in the Wiki.

Well, it will be possible for a single qutation like '>' I guess. But in case of multiple quotations with deeper levels e.g. '>>>' we need 3 lines/left borders on the left side if we want to stick to the same look as in XHTML.

Using a paragraph we could define different indentation and/or border color or maybe background color. But it will not be possible to have multiple borders (unless we insert graphics).

So, your idea is easier to implement. Using tables is more work but would give us the possibility to have the same look (or nearly the same). Not sure which way to go.

What do you think?

Regards,
Lars

**Comment by jlrn7** [comment]
I'm not sure I have understood, but it seems to me that each additional gt sign could produce a different paragraph style, each with greater left margin (not only indentation; I failed to express myself before). Think of Headings: each heading level has a different name, and eventually, different layout. I think you can add paragraph styles: > Quotation1, >> Quotation2, etc. The question is how many would be practicable.

Cheers,

**Comment by LarsGit223** [comment]
Yes, that's what I mean what can be done with paragraphs. I will go ahead and implement this approach.

Another approach would be tables or frames. With them we can have 1 border line for Qutation level 1, 2 border lines for qutation level 2...

But for now, I will go for the paragraphs. I checked the number list styles in LibreOffice. There are 5, so I will go for a max of 5 qutation levels with different indentation and border color for each.

Regards,
Lars

**Comment by LarsGit223** [comment]
Hello Louie,
I just created a new ODT release. Checkout the new quote style and let me know what you think.
Cheers, Lars

**Comment by jlrn7** [comment]
Hello! Looks OK to me. Works fine on Win7x64. I'll check my other WinTel machines back home and let you know if there is any trouble, but so far looks all right. Thanks!

**Comment by LarsGit223** [comment]
Hi,
thanks for the feedback. As soon as you confirmed that the rest of your machines are fine also, I will close this one.
Cheers.

**Comment by jlrn7** [comment]
Hello! The plugin works fine on WinXP/32 and Win7/64 and Win8/64. You may close this issue. Thanks.

**Comment by LarsGit223** [comment]
Great! Thanks for reporting the issue and sharing your ideas.
Have a nice day.
