### ISSUE TITLE
math feature request

### ISSUE THREAD

**Issue by jlrn7** [LarsGit223/dokuwiki-plugin-odt#32]
Hello! It would be neat if odt plugin could export mathematical expressions into *something* in odt, without having recourse to a full LaTeX+ installation. The slim MimeTeX would be a first option: so instead of calling LaTeX+ImageMagick+ghostscript to generate the image to include in the odt file, call the smaller (tiny by comparison) MimeTeX executable. Cheers!

**Comment by LarsGit223** [comment]
Hi,

I don't know if this is possible. Can you give me an example formula to test with? Which DokuWiki plugin do you use for displaying the math expression, e.g. math, mathjax, jsmath...?

I assume you need LaTeX+ or anything else anyway to display the expresiion for HTML also.

Regards,
Lars

**Comment by jlrn7** [comment]
Hello! 

The LaTeX plugin https://www.dokuwiki.org/plugin:latex promised to display maths as images, and when used with the odt plugin, to import these images into the odt file. However, after a few trials, and checking that the LaTeX plugin configuration is OK (the test runs smoothly), I can only make DokuWiki display the dreadful "LaTeX render failed" image, and export that image into the odt. 

My request would be to modify the odt plugin (or more likely, now that I've studied the problem a little bit, the mimeTeX plugin https://www.dokuwiki.org/plugin:mimetex), to make it do the math-to-image conversion thru mimeTeX, and insert the images into both the xhtml page rendered by DokuWiki, as it does it already, and into the odt exported file.

Cheers,

**Comment by LarsGit223** [comment]
Hello,

I just changed the mimetex plugin to support ODT rendering. The change still needs to be merged, watch the plugins github directory for further progress.

As this is not an issue of the ODT plugin itself, I close it now. The corresponding issue in the mimetex plugin is still open of course.

Bye,
Lars

**Comment by jlrn7** [comment]
After processing several documents I found out that the mimetex
executable lacks several symbols available through mathjax. Do you
think is it possible to inject mathjax's mathml output directly into
odt documents? This seems to be another practicable way to insert
maths into the odt converter. Cheers.

On 28/04/2015, LarsGit223 <notifications@github.com> wrote:
> Hi,
>
> I don't know if this is possible. Can you give me an example formula to test
> with? Which DokuWiki plugin do you use for displaying the math expression,
> e.g. math, mathjax, jsmath...?
>
> I assume you need LaTeX+ or anything else anyway to display the expresiion
> for HTML also.
>
> Regards,
> Lars
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LarsGit223/dokuwiki-plugin-odt/issues/32#issuecomment-97204896


-- 
Luis Rivera

**Comment by LarsGit223** [comment]
Hi.
I read a bit in the OpenDocument specification and it seems that it is possible to include MathML2.0 syntax in '<math:math>' tags.

I did a quick test but was not able to display a formula succesfully. Semms like it needs to be inserted in an Draw:object and that possibly needs to be inserted into a frame.

So, even though I did not suceed, the specification says it is supported.

Regards,
Lars

**Comment by jlrn7** [comment]
Hello! Do you mind sharing the code of your attempt? That way I may study this problem and may propose something concrete to the mathjax people. Thanks in advance. Luis.

**Comment by jlrn7** [comment]
Hello!

Perusing in different places, I found out:
1. That using mathjax is inherently hard: it implies 
a) calling the mathjax script, usually remotely; so it depends on the availability of an external server.
b) configuring mathjax to produce the desired output format (mathml as I suggested above) 
c) inserting the output in between the appropriate xml tags, which is no trivial task.
2. That the current implementation of ODT's math markup is still somewhat limited and/or buggy, compared to OOXML: several symbols are still missing and thus displayed as white squares (unrecognized glyphs).
So, even if theoretically possible, it seems like a long shot trying to teach the mathjax plugin to insert mathml into odt documents. It is simply easier to teach it to dump the original math expressions. I'll suggest that to the mathjax people.
This issue remains closed.

Cheers,

**Comment by LarsGit223** [comment]
Hi,
sorry for not reacting but I am currently concentrating my work on the wrap plugin.

I only had a look at an exported LibreOffice MathML formula and it seems they are inserting it as an object and a picture. Not as inline MathML as expected. I also found a posting in a developers forum for some tool about that and they had the same impression.

Did you contact the OpenOffice or LibreOffice team directly? If not let me know, I can give it a try. Maybe they can say something about future plans for it.

Regards,
Lars

**Comment by jlrn7** [comment]
Hello!

I've checked with ODTs generated by Pandoc and LibreOffice, and it seems that mathml expressions are indeed inserted in nested <draw:frame> and <draw:object> tags; but in both cases the objects are links to full xml documents containing the mathml expressions stored in their own subdirectories in the zipped file: so, for each mathematical expression it would be necessary to create a subfolder containing the equation in mathml code wrapped in a xml document. It looks pretty hard, especially for the dkw server.

However, I found out that both the flat odt (fodt) format and the odt format may contain the mathml code directly, inside tags exactly in that order: <draw:frame> <draw:object>. The resulting odt files don't display right (they seem to require additionally an automatically generated bitmap of the object) on LibreOffice, but they are rendered properly in MSWord.

Cheers,

**Comment by LarsGit223** [comment]
Hi,

I think it would be possible and not so hard. If someone can give the MathML code with a corresponding picture it shouldn't be that hard to insert it.

There is already a function which inserts a picture in the zip file and creates a link to it in the content.xml. Slightly modificated the same function could be used to insert the MathML code as an link/extra file.

That means, I could write a function in the ODT renderer class like 'insertMathML (code, picture)' and the caller only needs to specify the MathML code and a link to the picture. If you are interested in this, just let me know then I'll put it on the roadmap.

Cheers,
Lars

**Comment by jlrn7** [comment]
I know that MathJax can return both MathML code and SVG graphics, and apparently ODT supports the inclusion of both MathML code and SVG graphics; so the solution seems to involve calling MathJax twice: once to return the math expression and another for the graphics file.

You may put this suggestion in your roadmap. That seems to be a better solution than simply including the gif produced by mimeTeX (which, by the way, seems to have been abandoned for mathTeX, which involves the whole LaTeX+dvips+ghostscript+imagemagick dance again).

Cheers,
