### ISSUE TITLE
remove old zip class?

### ISSUE THREAD

**Issue by Klap-in** [LarsGit223/dokuwiki-plugin-odt#42]
Is it fine for you if I remove the old ZipLib class?

**Comment by LarsGit223** [comment]
I just wrote an e-mail at the mailing list about backwards compatibility for plugins about an hour ago. Let's wait for the reactions.

**Comment by Klap-in** [comment]
The default deprecation policy is described here: https://www.dokuwiki.org/devel:releases#deprecation

With about 2 releases a year stuff could work about an year without improving, and often 2 years is possible. But because it is very recommended to use the latest version it is fine to move further and remove/replace the old stuff in the third release.

(and also there are plugins that don't care for backward compatibility, due to the maintenance burden...)

**Comment by LarsGit223** [comment]
Ok, then let's throw it out :-)

**Comment by Klap-in** [comment]
Who will doing that?

**Comment by LarsGit223** [comment]
I can do that. I will start working on it tomorrow.

**Comment by LarsGit223** [comment]
Done (on branch bookcreator).
