### ISSUE TITLE
config settings global and per wikipage

### ISSUE THREAD

**Issue by Klap-in** [LarsGit223/dokuwiki-plugin-odt#55]
Some pull requests add some config options. e.g. #54 and #53

Probably it useful to refactor the configuration possibilities a bit, which allows to set global settings via the Configuration Manager, document settings per url-paramaters or per pages via the syntax.

**Comment by LarsGit223** [comment]
You mean it's too much?

But for most things I agree it is nice to have a config option and a syntax option. Most users might be happy with a global config option. For advanced usage the config options through the syntax are neccessary (in my opinion).

E.g. for page format (e.g. A4) and orientation (e.g. 'portrait)' I would prefer to have both. A global config option giving the default start value, and a syntax option to change it per page in between a document.

**Comment by Klap-in** [comment]
My suggestion is to have global *and* via url parameters *and* via syntax in the page. Which just override each other.

I observe some options have now a global config possibility and others not. Therefore my suggestion is to refactor the code of all the config settings after the merge of the outstanding pull requests. That way the code becomes simpler, and the configurations possibilities more consistent.

**Comment by LarsGit223** [comment]
Ok, to continue on this we first need an overview of all currently used config options:

**Directory of the templates in the media manager:**
- global config option: Yes -> **'tpl_dir'**
- URL config option: No
- syntax config option: No

**Default template (filename only):**
- global config option: Yes -> **'tpl_default'**
- URL config option: Yes -> **'odt-template'**
- syntax config option: Yes -> **'{{odt>template}}'**

**Display the export button?:**
- global config option: Yes -> **'showexportbutton'**
- URL config option: No
- syntax config option: No

**Media selector for CSS import:**
- global config option: Yes -> **'media_sel'**
- URL config option: No
- syntax config option: No

**DokuWiki-Template for CSS import:**
- global config option: Yes -> **'template'**
- URL config option: No
- syntax config option: No

**Lists of plugins for import of screen CSS styles:**
- global config option: Yes -> **'usestyles'**
- URL config option: No
- syntax config option: No

**Converting pixel to points, X-Axis:**
- global config option: Yes -> **'twips_per_pixel_x'**
- URL config option: No
- syntax config option: No

**Converting pixel to points, Y-Axis:**
- global config option: Yes -> **'twips_per_pixel_y'**
- URL config option: No
- syntax config option: No

**Table of contents:**
- global config option: No
- URL config option: No
- syntax config option: Yes -> **'{{odt>toc}}'**

**Maximum TOC level:**
- global config option: Yes -> **'maxtoclevel'**
(global DokuWiki config option)
- URL config option: No
- syntax config option: Yes, as part of -> **'{{odt>toc}}'**

**Disable/Enable-Links:**
- global config option: No
- URL config option: No
- syntax config option: Yes -> **'{{odt>disablelinks}}'**, **'{{odt>enablelinks}}'**

**Set page format:**
- global config option: No
- URL config option: No
- syntax config option: Yes -> **'{{odt>page}}'**

**Directories:**
'mediadir', 'datadir', 'savedir' (deprecated), 'tmpdir'
(global DokuWiki config options)

**Use headings:**
- global config option: Yes -> **'useheading'**
(global DokuWiki config option)
- URL config option: No
- syntax config option: No

**Date format:**
- global config option: Yes -> **'dformat'**
(global DokuWiki config option)
- URL config option: No
- syntax config option: No

**Comment by Klap-in** [comment]
Handy overview!

At the dw2pdf plugin recently @fayan opened a pull request [1] for adding support for his Settingstree Plugin [2]. Maybe a nice idea to investigate how we can collaborate with him when looking in the config settings of the ODT plugin.

[1] https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/pull/204
[2] https://www.dokuwiki.org/plugin:settingstree

**Comment by LarsGit223** [comment]
I looked at the config options and I think the following options should stay as they are and should not get a global/URL/syntax combination:

**Directories:**
'mediadir', 'datadir', 'savedir' (deprecated), 'tmpdir'
(global DokuWiki config options)

**Date format:**

    global config option: Yes -> 'dformat' (global DokuWiki config option)
    URL config option: No
    syntax config option: No

**Use headings:**

    global config option: Yes -> 'useheading' (global DokuWiki config option)
    URL config option: No
    syntax config option: No

**Display the export button?:**

    global config option: Yes -> 'showexportbutton'
    URL config option: No
    syntax config option: No

**Directory of the templates in the media manager:**

    global config option: Yes -> 'tpl_dir'
    URL config option: No
    syntax config option: No

These are mainly global settings that in my opinion do not relate to a single document.

**Comment by LarsGit223** [comment]
Regarding **Table of contents**:

The TOC itself can only be syntax tag. That means I can not implement an option like "insert a TOC on page 5" because the ODT plugin is "only" generating an XML-ODT document but it does not render the pages and doesn't know it's current position/page number when exporting a wiki article.

But the TOC syntax tag can carry settings that might be useful to configure:
- maxtoclevel, overwrites global DokuWiki maxtoclevel so only URL option is missing
- title
- leader-sign (signs between the chapter and the page number e.g. "chapter A........5")
- indents (indentation per toc-level)
- pagebreak after TOC?
- CSS styles per TOC level

**Comment by LarsGit223** [comment]
Just for your information:
I created a branch 'config' for working on the configuration settings.

**Comment by LarsGit223** [comment]
Hi Klapp-in,

I'm still working on the config refactoring and just moved the config handling to a helper class 'odt_config'. This enables me to query a simple md5 hash for the currently stored config settings. I hoped this would make it simple to invalidate the cache if the configuration changes. Take a look at the changes I tried in export.php (I didn't commit these because it doesn't work):

```diff
@@ -17,6 +17,7 @@
  * Collect pages and export these. GUI is available via bookcreator.
  */
 class action_plugin_odt_export extends DokuWiki_Action_Plugin {
+    protected config = NULL;
 
     /**
      * @var array
@@ -221,14 +222,21 @@
         global $REV;
         global $INPUT;
 
+        // Load config helper if not done yet
+        if ( $this->config == NULL ) {
+            $this->config = plugin_load('helper', 'odt_config');
+        }
+
         //different caches for varying config settings
-        $template = $this->getConf("odt_template");
-        $template = $INPUT->get->str('odt_template', $template, true);
+        //$template = $this->getConf("odt_template");
+        //$template = $INPUT->get->str('odt_template', $template, true);
+        $this->config->load();
+        $hash_value = $this->config->hash();
 
 
         $cachekey = join(',', $this->list)
             . $REV
-            . $template
+            . $hash_value
             . $title;
         $cache = new cache($cachekey, '.odt');
 ```

But this doesn't have any effect because it only changes the cachekey. I don't know how the cache exactly works and I want to concentrate on the config refactoring. So I thought I write these lines for you to have a look.

Have you got any idea for a simple change to invalidate the cache if the config hash changes?

Right now, there is no effect. E.g. if I export a document using URL param ```&format=A3``` and after that again with ```&format=A4```, then I get the same document even though the config changed.

Cheers,
Lars

**Comment by Klap-in** [comment]
If one have limited sets of (used) settings (that does not change often) it could be useful to have a cachefile for each settings combination.
Otherwise it is more useful to disable caching. Because it accumulate many cached files, which are not often used.

**Comment by LarsGit223** [comment]
Ok, makes sense. Then I will keep your original code unchanged.
Thanks.

**Comment by LarsGit223** [comment]
I think I'm done so far.

I was thinking about maybe having a config option for the toc title. But the title right now is taken from the language settings. Do you think it might be useful to have a config option to overwrite the language setting? Of course the title can also be set in the toc syntax tag already.

**Comment by LarsGit223** [comment]
So here is an update to the overview. This is the current state of play in branch **config**:

**Directory of the templates in the media manager:**
- global config option: Yes -> **'tpl_dir'**
- URL config option: No
- syntax config option: No

**Default template (filename only):**
- global config option: Yes -> **'odt_template'**
- URL config option: Yes -> **'odt_template'**
- syntax config option: Yes -> **'{{odt>odt_template}}'**

**Display the export button?:**
- global config option: Yes -> **'showexportbutton'**
- URL config option: No
- syntax config option: No

**Media selector for CSS import:**
- global config option: Yes -> **'media_sel'**
- URL config option: Yes -> **'media_sel'**
- syntax config option: Yes -> **'{{odt>media_sel}}'**

**DokuWiki-Template for CSS import:**
- global config option: Yes -> **'css_template'**
- URL config option: Yes -> **'css_template'**
- syntax config option: Yes -> **'{{odt>css_template}}'**

**Lists of plugins for import of screen CSS styles:**
- global config option: Yes -> **'usestyles'**
- URL config option: Yes -> **'usestyles'**
- syntax config option: Yes -> **'{{odt>usestyles}}'**

**Converting pixel to points, X-Axis:**
- global config option: Yes -> **'twips_per_pixel_x'**
- URL config option: Yes -> **'twips_per_pixel_x'**
- syntax config option: Yes -> **'{{odt>twips_per_pixel_x}}'**

**Converting pixel to points, Y-Axis:**
- global config option: Yes -> **'twips_per_pixel_y'**
- URL config option: Yes -> **'twips_per_pixel_y'**
- syntax config option: Yes -> **'{{odt>twips_per_pixel_y}}'**

**Page format:**
- global config option: Yes -> **'format'**
- URL config option: Yes -> **'format'**
- syntax config option: Yes -> **'{{odt>format}}'**

**Page orientation:**
- global config option: Yes -> **'orientation'**
- URL config option: Yes -> **'orientation'**
- syntax config option: Yes -> **'{{odt>orientation}}'**

**Page top margin:**
- global config option: Yes -> **'margin_top'**
- URL config option: Yes -> **'margin_top'**
- syntax config option: Yes -> **'{{odt>margin_top}}'**

**Page right margin:**
- global config option: Yes -> **'margin_right'**
- URL config option: Yes -> **'margin_right'**
- syntax config option: Yes -> **'{{odt>margin_right}}'**

**Page bottom margin:**
- global config option: Yes -> **'margin_bottom'**
- URL config option: Yes -> **'margin_bottom'**
- syntax config option: Yes -> **'{{odt>margin_bottom}}'**

**Page left margin:**
- global config option: Yes -> **'margin_left'**
- URL config option: Yes -> **'margin_left'**
- syntax config option: Yes -> **'{{odt>margin_left}}'**

**Set all page params at once:**
- global config option: No
- URL config option: Yes -> **'page'**
- syntax config option: Yes -> **'{{odt>page}}'**

**Disable links:**
- global config option: Yes -> **'disable_links'**
- URL config option: Yes -> **'disable_links'**
- syntax config option: Yes -> **'{{odt>disable_links}}'**, **'{{odt>enable_links}}'**

**Set all Table of contents parameters as once and insert TOC:**
- global config option: No
- URL config option: No
- syntax config option: Yes -> **'{{odt>toc}}'**

**TOC: Maximum level:**
- global config option: Yes -> **''toc_maxlevel''**
- URL config option: Yes -> **''toc_maxlevel''**
- syntax config option: Yes -> **'{{odt>toc_maxlevel}}'**
This option first inherits it's value from DokuWiki's global config param 'maxtoclevel'. After that it takes a look at the plugin config, URL and syntax tag.

**TOC: leader_sign:**
- global config option: Yes -> **''toc_leader_sign''**
- URL config option: Yes -> **''toc_leader_sign''**
- syntax config option: Yes -> **'{{odt>toc_leader_sign}}'**

**TOC: indents:**
- global config option: Yes -> **''toc_indents''**
- URL config option: Yes -> **''toc_indents''**
- syntax config option: Yes -> **'{{odt>toc_indents}}'**

**TOC: pagebreak after TOC?:**
- global config option: Yes -> **''toc_pagebreak''**
- URL config option: Yes -> **''toc_pagebreak''**
- syntax config option: Yes -> **'{{odt>toc_pagebreak}}'**

**TOC: default text style for all levels:**
- global config option: Yes -> **''toc_style''**
- URL config option: Yes -> **''toc_style''**
- syntax config option: Yes -> **'{{odt>toc_style}}'**
Specific styles per level can be set using **'{{odt>toc}}'**

**Directories:**
'mediadir', 'datadir', 'savedir' (deprecated), 'tmpdir'
(global DokuWiki config options)

**Use headings:**
- global config option: Yes -> **'useheading'**
(global DokuWiki config option)
- URL config option: No
- syntax config option: No

**Date format:**
- global config option: Yes -> **'dformat'**
(global DokuWiki config option)
- URL config option: No
- syntax config option: No

**Comment by LarsGit223** [comment]
@Klap-in:

Could I ask you for the favour to have a look at this and give me your opinion on it/suggestions for improvements?

I'm a bit concerned about the name of the ODT template config parameter changing from **template** to **odt_template**. Do you think that will be a big issue/inconvenience for the users? But I really think it's better to have a clear name to differ between the ODT and the dokuwiki template.

I didn't use the settingstree yet. I didn't have a deeper look at it yet. Right now I would like to merge this to the master branch if you have nothing to add and then have a new release.

There are quite a lot of features not released yet:
- enable/disablelinks
- bookcreator support
- TOC support
- improved link generation inside the ODT document
- change of page format

I would like to release this and update the documentation before doing more changes.

**Comment by Klap-in** [comment]
Settingstree plugin is a quite extended and relative complex plugin. So not directly implementing is fine. 

The coming weeks I will not have internet, so I cannot review in that time. Maybe I have this weekend a bit of time..

**Comment by Klap-in** [comment]
I did read through quickly the code of the changes since the last release. Sofar I didn't spot undesired issues. 

With respect to `odt_template` vs `template`: could you still support the template variable for some time? Is it possible to add set a msg() if it is used, with an explanation that the url-parameter is deprecated, and has to be updated?

Or maybe simpeler: if the `template` url is used, just display an error with msg() and do not perform an export? I think a kind of feedback that stuff should be updated could be useful. 

Or a bit more gradually: first for a half of a year or a year a warning and still export, and after that period a warning without continuing the export.

**Comment by LarsGit223** [comment]
Ok! Thanks a lot for having a look!

Hmmm...if I remember right I tried using msg() before. Is that possible?

The data the plugin sents over HTTP is the ODT document itself so I think I can not display a msg() AND deliver the ODT document.

The original code displayed a message inside the exported document so maybe I'll do that. Thanks for your feedback!

**Comment by Klap-in** [comment]
If you use msg() the message is stored. This stored message is kept as long as it is not displayed. When it is displayed it is removed. During an export, errors are not displayed, but during an normal page view errors are displayed because there `html_msgarea()` is called.

I wouldn't include warnings inside documents. I think the messages should be shown to the user of the export function, and not to the the reader of the document.

If an export is triggered, only the document is delivered as download, but the page is not reloaded?
Eventually (not ideal case...) we could consider that the page should be reloaded after a document is reloaded.. (no idea whether this is technical practical to implement).

So maybe the easiest solution is to just stop the export and show a warning. (despite that it derogates the user experience)

**Comment by LarsGit223** [comment]
For now, I did implement the simple solution. That means the export stops if the template is not found and the message is displayed.

I thinks that's it for know so I close this issue.
