### ISSUE TITLE
How do you use plugin»odt»usestyles option?

### ISSUE THREAD

**Issue by limelime** [LarsGit223/dokuwiki-plugin-odt#61]
How do you use plugin»odt»usestyles option?

*  I set `plugin»odt»media_sel` to `screen`.
*  I set `plugin»odt»usestyles` to `print.css,odt.css`.

Both `print.css` and `odt.css` in my `../conf/` are:
```
body {
    color: yellow;
}

@media screen{
  body {
    color: lightblue;
  }
}

@media screen and (max-width: 300px) {
  body {
      background-color: lightblue;
  }
}
```
*  Clear the cache by clicking on Save configuration.
*  Export ODT file. There is no color at all. The only style that I got is bold and links are hyperlinked.

**Comment by LarsGit223** [comment]
I assume you want to change some baisc properties?

This is currently not working because right now, only some plugins use the CSS imported by the ODT plugin (e.g. wrap, exttab3, typography).

If you mean something else, please let me know.

**Comment by limelime** [comment]
Yes, I want to change some basic properties.

>This is currently not working because right now, only some plugins use the CSS imported by the ODT plugin (e.g. wrap, exttab3, typography).

I'm confused with your statement. I'm not using other plugins. Do you mean that by default, ODT plugin doesn't process the default CSS of Dokuwiki?

**Comment by LarsGit223** [comment]
Yes. Or let's say it is processing and importing it but not using it. That means the ODT plugin has currently not got the capability/feature bilt in to genereate the styles for the basic DokluWiki elements like normal tables, lists, headings etc... This is future work and will not be available in the near future. But it is my plan to implement it.

**Comment by LarsGit223** [comment]
Do you have any further questions? Can I close this?

**Comment by LarsGit223** [comment]
@limelime:
The current master now supports CSS templateing for the basic DokuWiki syntax.

To start with it do the following:
  - upload or copy the file 'example.css' to your template directory (see config option **tpl_dir**)
  - you need to change your mime.conf file to be allowed to upload CSS files with the media manager, see documentation @dokuwiki.org
  - set the file as the ODT template in the configuration (or per syntax, see updated ODT plugin page @dokuwiki.org). The ODT template can now be a .ODT or a .CSS file.

There is still a lot of things that need to be improved regarding styles but basic things work now. It should be no problem to change the text color or table background-color for example.
