### ISSUE TITLE
Add table header background color

### ISSUE THREAD

**Issue by limelime** [LarsGit223/dokuwiki-plugin-odt#62]
How do you add background color to table header?

Using odt template doesn't work because Writer doesn't support style on the cell property. https://forum.openoffice.org/en/forum/viewtopic.php?f=7&t=60740

Is there a way to overcome this with dokuwiki-plugin-odt?

**Comment by LarsGit223** [comment]
Please have a look at the exttab3 plugin.

**Comment by LarsGit223** [comment]
Did this help you or have you got any firther questions? Do you mind closing this issue?
