### ISSUE TITLE
geshi has moved

### ISSUE THREAD

**Issue by chtiland** [LarsGit223/dokuwiki-plugin-odt#68]
Error when generating ODT file : 
require_once(xxx/inc/geshi.php): failed to open stream: No such file or directory in /xxx/lib/plugins/odt/renderer.php on line 1352

geshi.php is in /xxx/vendor/easybook/geshi/

**Comment by Klap-in** [comment]
Do you use the last version of this plugin?

**Comment by chtiland** [comment]
I think so : 
plugin.info.txt : date   	2015-06-28

In fact, when I get archive from https://www.dokuwiki.org/plugin:odt, I don't have the same content than the one I download from github.
In the first one I got a renderer.php file, but not in the second one (I got a renderer folder).

**Comment by LarsGit223** [comment]
The require once line is included in the latest release. It is not present any more in the master branch/development version.

I made sure that directory **inc/geshi** doesn't exist on my installation. But still both versions work fine anyway!?!

I assume the content causing the error is a simple ```<code ...>...</code>``` section?

**Comment by Klap-in** [comment]
The `require_once(xxx/inc/geshi.php)` is superfluous. DokuWiki has an autoloader that will find in the last release and in the previous releases of DokuWiki the correct geshi.php file.

So solution: just remove the line with the require_once from renderer.php.

**Comment by LarsGit223** [comment]
Ok, then there is nothing to do - it has already been removed from **master** before.

It is only present in the latest release.

**Comment by LarsGit223** [comment]
But why doesn't it work with chtiland's installation?

**Comment by Klap-in** [comment]
Because the hardcode require_once(xxx/inc/geshi.php) requests a wrong location. Since the last release that location is changed to  /xxx/vendor/easybook/geshi/, so this hard coded path is wrong.
If he removes that line, DokuWiki's autoloading will find the path itself.

**Comment by chtiland** [comment]
Or simply because download link on https://www.dokuwiki.org/plugin:odt point to https://github.com/LarsGit223/dokuwiki-plugin-odt/archive/2015-06-29.zip wich is not the last version (different from Master)

**Comment by Klap-in** [comment]
In this repository the releases are stored separately as release. At this way the master could heading the release, which gives the opportunity to test it more extensive.
See also https://github.com/LarsGit223/dokuwiki-plugin-odt/releases

**Comment by LarsGit223** [comment]
@chtiland:
The development master has just been released as official 2015-10-03 release. So you don't need to download from github any longer.
