### ISSUE TITLE
Added wiki page Manipulate-ODT-file

### ISSUE THREAD

**Issue by limelime** [LarsGit223/dokuwiki-plugin-odt#75]
Just to let you know. I started to add what I have learned about this plugin on the wiki page of your project. I hope that you don't mind. Feel free to delete it if you don't want it.

https://github.com/LarsGit223/dokuwiki-plugin-odt/wiki/Manipulate-ODT-file

Is there a way to send email directly to the user instead of creating an issue?

**Comment by LarsGit223** [comment]
You can send e-mail to my address from the DokuWiki forum, user LarsDW223.

Of course you are welcome to contribute. Did you see this page also:
https://www.dokuwiki.org/plugin:odt:rendersupport.

**Comment by LarsGit223** [comment]
Keep in mind that it's also not a bad idea to ask questions here, so others can read and learn from it or share their answers/knowledge with you/us.
