### ISSUE TITLE
Add a separation between subsequent lists

### ISSUE THREAD

**Issue by limelime** [LarsGit223/dokuwiki-plugin-odt#76]
Add a separation between subsequent lists. The webpage does have separation but not in ODT.
```
~~NOCACHE~~
  - list 1 - item 1
  - list 1 - item 2
  - list 1 - item 3

  - list 2 - item 1
  - list 2 - item 2
  - list 2 - item 3

Nested list should not have separation:

  - list 1 - item 1
  - list 1 - item 2
    - nested list - item 1
    - nested list - item 2
  - list 1 - item 3
```

**Comment by LarsGit223** [comment]
Just like in HTML there are no elements between the two lists. The generated ODT XML code looks like this:
```
<text:list text:style-name="Numbering_20_1">
    <text:list-item><text:p text:style-name="Text_20_body"> list 1 - item 1</text:p></text:list-item>
    <text:list-item><text:p text:style-name="Text_20_body"> list 1 - item 2</text:p></text:list-item>
    <text:list-item><text:p text:style-name="Text_20_body"> list 1 - item 3</text:p></text:list-item>
</text:list>
<text:list text:style-name="Numbering_20_1">
    <text:list-item><text:p text:style-name="Text_20_body"> list 2 - item 1</text:p></text:list-item>
    <text:list-item><text:p text:style-name="Text_20_body"> list 2 - item 2</text:p></text:list-item>
    <text:list-item><text:p text:style-name="Text_20_body"> list 2 - item 3</text:p></text:list-item>
</text:list>
```

So this problem will be related to the style given to the list.

**Comment by LarsGit223** [comment]
I played around a bit with LibreOffice.

It seems the only way to solve this would be to assign different styles to the list items. The first paragraph in a list would need to have its own style, and the last one and all items in the middle need to have a third style. So the first one and last one can have top and bottom margins without separating the list items towards each other.

**Comment by LarsGit223** [comment]
I added an extra style for the first paragraph of a list. This will set a 0.5 cm top margin to separate the list from the previous content.

**Comment by LarsGit223** [comment]
For your information:
I just added a new style for the last paragraph of a list. So you can now also easily control the distance to the content following a list. (only in master branch)
