### ISSUE TITLE
PHP runtinme error

### ISSUE THREAD

**Issue by wernerflamme** [LarsGit223/dokuwiki-plugin-odt#78]
PHP Fatal error:  Can't use method return value in write context in /srv/www/dokuwiki/lib/plugins/odt/helper/config.php on line 519, referer: https://linux.myhost/dokuwiki/doku.php

After editing a wiki page, the page is not displayed any more, just blank screen. Changes are lost. It is PHP 5.3.17 on a SLES 11 SP3 box.

After commenting in the code from line 519 to 529, the same error comes up with line 532. Commenting in this section (532-541), the error appears in line 565. Here I comment out 565-567, and everythings works again. For me this is not a problem, since I do not use templates anyway... I'd like an official workaround though :)

**Comment by LarsGit223** [comment]
What odt plugin configuration settings do you make to produce the problem?

**Comment by LarsGit223** [comment]
Ok, I didn't get the error because I use PHP 5.6.4.

The error only occurs with PHP versions below 5.5. Also see http://stackoverflow.com/questions/1075534/cant-use-method-return-value-in-write-context for more information.

Please re-test with your PHP version. Thanks.

**Comment by wernerflamme** [comment]
Hi, yes, it works fine now :). I already thought that it might be related to my antique version of PHP. Unfortunately, I'm currently stuck with SLES 11 and its PHP 5.3. SLE 12 has PHP 5.5, but I can't update now, the machine has  other things to do as well. Thank you for your efforts!

**Comment by LarsGit223** [comment]
You are welcome. I guess there are many other people who also use older PHP versions for various reasons. So thanks for reporting the error!

**Comment by wernerflamme** [comment]
I couldn't help reporting the issue :). With other plugins, I'd just deactivate them, but ODT is so useful that I can't use this simple solution :)

BTW, in the conf subdir of my DW installation, a "grep -rin odt *" only returns one line, and that is line 53 of mime.conf. So I did not configure anything with the ODT plugin, the defaults should still be honoured.
