### ISSUE TITLE
Bookmark is created but it is not hyperlinked

### ISSUE THREAD

**Issue by limelime** [LarsGit223/dokuwiki-plugin-odt#81]
See example below. I expected **Anchor** to be hyperlinked but it is not.
```
~~NOCACHE~~

====== Test anchor/bookmark ======
Please refer to [[#anchor| Anchor]] section below.

====== Anchor ======
Test anchor/bookmark.

```

**Comment by LarsGit223** [comment]
Done, should work now.

The anchor name was not found in the list of bookmarks and so the link to the heading could not be created. The anchor name needs to be trimmed in case there are any leading or following spaces and it needs to be converted to small letters to match the bookmarks.
