### ISSUE TITLE
enablelinks/disablelinks reports PHP error

### ISSUE THREAD

**Issue by andyboeh** [LarsGit223/dokuwiki-plugin-odt#94]
Setting {{odt>disablelinks}} results in an error in the PHP log: PHP Fatal error:  no such method setParam. 

In renderer/page.php, in disable_links/enable_links, it should read $this->config->setParam(..) instead of $this->setParam(..).

**Comment by LarsGit223** [comment]
Sorry, oversaw that two calls. All other calls to setParam() / getParam() seem to be okay.

**Comment by andyboeh** [comment]
That was fast, thanks!
