### ISSUE TITLE
Table column width?

### ISSUE THREAD

**Issue by andyboeh** [LarsGit223/dokuwiki-plugin-odt#95]
I added support for exporting to ODT in the data plugin (Currently at PR splitbrain/dokuwiki-plugin-data/pull/169) a few weeks ago. The data plugin allows to specify the column width for its HTML output and I wanted to implement that for ODT as well.

Is there already support for specifying the column width? If not, how could I add that?

Thanks

**Comment by LarsGit223** [comment]
Not with the "classic" functions you mentioned. These are also called from the parser so there are no parameters at all that can be passed to the functions.

You should have a look at this functions:
_odtTableOpenUseCSS, _odtTableOpenUseCSSStyle, _odtTableOpenUseProperties,
_odtTableHeaderOpenUseCSS, _odtTableHeaderOpenUseCSSStyle, _odtTableHeaderOpenUseProperties, _odtTableAddColumnUseProperties, _odtTableRowOpenUseCSS, _odtTableRowOpenUseCSSStyle, _odtTableRowOpenUseProperties,
_odtTableCellOpenUseCSS, _odtTableCellOpenUseCSSStyle, _odtTableCellOpenUseProperties, 

With that functions it should be possible to set the width, e.g. by passing it in the property array ```$properties ['width'] = '5cm';```. For an example usage see the exttab3 plugin.

**Comment by LarsGit223** [comment]
If you need more information, just let me know.

**Comment by LarsGit223** [comment]
Have you got any further questions or can I close this?

**Comment by andyboeh** [comment]
Of course, it can be closed. I haven't had the time to look into it, but your comments make sense to me. Thanks!

**Comment by LarsGit223** [comment]
You are welcome. If you got any questions on this topic later, just re-open it.
