### ISSUE TITLE
Install issue 

### ISSUE THREAD

**Issue by bollonjm** [LarsGit223/dokuwiki-plugin-odt#96]
After install I get 
Fatal error: Can't use method return value in write context in C:\Users\Compaq\Downloads\dokuwiki-460ee2279ccc3e08c706c287598b2298\DokuWikiStick\dokuwiki\lib\plugins\odt\helper\config.php on line 569

The dokuwiki is down after, must remove the plugin folder

**Comment by LarsGit223** [comment]
This problem has already been solved in the current master/development branch.

You can solve it by:
- updating to PHP 5.5 or higher
- use the ODT plugin master branch (needs to be installed manually)

Change the lines in config.php from
```
$template = $this->getParam ('template');
$odt_template = $this->getParam ('odt_template');
if (!empty($this->getParam ('template')) && empty($this->getParam ('odt_template'))) {
    $this->setParam ('odt_template', $this->getParam ('template'));
}
```
to
```
$template = $this->getParam ('template');
$odt_template = $this->getParam ('odt_template');
if (!empty($template) && empty($odt_template)) {
    $this->setParam ('odt_template', $this->getParam ('template'));
}
```

**Comment by LarsGit223** [comment]
Please also see **PHP runtinme error** #78.

**Comment by LarsGit223** [comment]
Did this information help you? Can I close this issue or do you need further assistance?

**Comment by DarioGT** [comment]
PHP 5.3.3 (cli) (built: Jul  3 2015 03:10:33) 
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies


Ok,  Thk
