### ISSUE TITLE
List item numeration is the same on all levels

### ISSUE THREAD

**Issue by LarsGit223** [LarsGit223/dokuwiki-plugin-odt#97]
If a page with a nested numbered list is exported to ODT, then all levels have the same enumeration format.

A nested enumerated list in the browser will render like this:
```
1. List 1-Item-1
  a. List 2-Item-1
  b. List 2-Item-2
  c. List 2-Item-3
2. List 1-Item-2
3. List 1-Item-3
```
After export to ODT it will look like this:
```
1. List 1-Item-1
  1. List 2-Item-1
  2. List 2-Item-2
  3. List 2-Item-3
2. List 1-Item-2
3. List 1-Item-3
```

**Comment by LarsGit223** [comment]
Now the enumeration is like in the browser:

- For level 1: 1. 2. 3.
- For level 2: a. b. c.
- For level 3: I. II. III.
- For level 4: A. B. C.
- For level 5: i. ii. iii.
- For level 6 to 10: same as level 5

**Comment by tytax** [comment]
Thank you for that. But could you do that numbered lists and bulleted lists highlight as special style distinct from the main text. This makes it easier to format dokument in OpenOffice. Sorry for my English and thank you in advance.
